### ISSUE TITLE
make public isCellType function

### ISSUE THREAD

**Issue by klitsner** [fjenett/xlsreader-library-processing#11]
It would be very useful to be able to check a cell for the type of its contents. If a column contains both int and string data types, there currently seems to be no way of checking.

**Comment by fjenett** [comment]
Yes, good point

**Comment by markusand** [comment]
It would be nice if other functions like selectRow() or getLastCellNum() could also be public

**Comment by fjenett** [comment]
Added a new method to get the type of a cell as string. You can alter `simple example 1` like this to see it in action:

```
println( reader.getCellType( 1, 0 ), reader.getString( 1, 0 ) );
println( reader.getCellType( 2, 0 ), reader.getInt( 2, 0 ) );
println( reader.getCellType( 3, 0 ), reader.getFloat( 3, 0 ) );
```
