### ISSUE TITLE
zip file doesn't follow processing library guidelines for folder structure

### ISSUE THREAD

**Issue by josephtaylor** [fjenett/xlsreader-library-processing#12]
https://github.com/processing/processing/wiki/Library-Guidelines#folder-structure

`source` should be `src`
`documentation` should be `reference`

**Comment by q2dg** [comment]
In fact, this library isn't compatible with Processing 3.
Will it be someday?
Thanks!

**Comment by josephtaylor** [comment]
I manually installed the library and was able to run all the examples in Processing 3 without any errors.  I'm not sure exactly why the library is grayed out in the Contributed Libraries popup in the UI. It may be that somebody just needs to tell the processing maintainers that it's working.
